name: Build Cork on macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Cork
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2.0'

    - name: Build Cork
      run: |
        xcodebuild -project Cork.xcodeproj -scheme Cork -configuration Release -sdk macosx build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

    - name: Archive Cork
      run: |
        xcodebuild -project Cork.xcodeproj -scheme Cork -configuration Release -sdk macosx archive -archivePath ./build/Cork.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

    - name: Export Cork App
      run: |
        xcodebuild -exportArchive -archivePath ./build/Cork.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build
      env:
        XCODE_DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CorkApp
        path: ./build/Cork.app
