name: Build Cork for macOS

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install cmake
          brew install boost
      - name: Build Cork
        run: |
          mkdir build
          cd build
          cmake ..
          make
        shell: /bin/bash -e {0}
