name: Usuń błędy w Cork

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Usuń plik CMakeCache.txt
        run: |
          rm -rf CMakeCache.txt
      - name: Utwórz nowy katalog budowania
        run: |
          mkdir build
          cd build
      - name: Uruchom CMake
        run: |
          cmake ..
      - name: Skompiluj Cork
        run: |
          make
