name: Budowa Cork na macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Budowa Cork
    runs-on: macos-latest

    steps:
    - name: Pobierz kod
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: true
        --node-version: 20

    - name: Skonfiguruj Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Zbuduj Cork
      run: |
        xcodebuild -project Cork.xcodeproj -scheme Cork -configuration Release -sdk macosx build ARCHS=arm64 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

    - name: Archiwizuj Cork
      run: |
        xcodebuild -project Cork.xcodeproj -scheme Cork -configuration Release -sdk macosx archive -archivePath ./build/Cork.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"

    - name: Eksportuj aplikację Cork
      run: |
        xcodebuild -exportArchive -archivePath ./build/Cork.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build

    - name: Archiwizuj artefakty budowania
      uses: actions/upload-artifact@v2
      with:
        name: CorkApp
        path: ./build/Cork.app
