name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_14.2.0.app

    - name: Install dependencies
      run: |
        brew install glfw3
        brew install glew

    - name: Build Project
      run: |
        xcodebuild -project Cork.xcodeproj -alltargets -configuration Release build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
