name: Build Cork on macOS with Homebrew

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Cork
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main
        submodules: true

    - name: Install Homebrew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install Xcode
      run: brew install xcode

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Cork dependencies
      run: npm install

    - name: Build Cork
      run: xcodebuild -project Cork.xcodeproj -scheme Cork -configuration Release -sdk macosx build ARCHS=arm64 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""

    - name: Archive Cork
      run: xcodebuild -project Cork.xcodeproj -scheme Cork -configuration Release -sdk macosx archive -archivePath ./build/Cork.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS=""

    - name: Export Cork App
      run: xcodebuild -exportArchive -archivePath ./build/Cork.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./build

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CorkApp
        path: ./build/Cork.app
